# Generated by Django 2.0.2 on 2018-02-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorm_name', models.CharField(help_text='Enter dorm name', max_length=50)),
                ('dorm_description', models.TextField(help_text='Enter dorm description', max_length=1000)),
                ('dorm_primary_picture', models.ImageField(help_text='Enter dorm primary pic', upload_to='')),
                ('dorm_room_count', models.IntegerField(help_text='Enter no. of rooms')),
                ('dorm_address', models.CharField(help_text='Enter dorm address', max_length=100)),
                ('dorm_caretaker', models.CharField(help_text='Enter caretaker name', max_length=50)),
                ('dorm_contact_no', models.CharField(help_text='Enter dorm contact number', max_length=50)),
                ('dorm_contact_email', models.EmailField(help_text='Enter dorm email', max_length=254)),
                ('dorm_date_added', models.DateTimeField(help_text='Enter Date Dorm was created')),
                ('dorm_availability', models.CharField(help_text='Is dorm available', max_length=50)),
                ('dorm_date_updated', models.DateTimeField(help_text='Enter Date Dorm information was updated')),
                ('dorm_house_rules', models.TextField(help_text='Enter dorm house rules', max_length=1000)),
            ],
            options={
                'ordering': ['-dorm_name'],
            },
        ),
    ]
