# Generated by Django 2.0.2 on 2018-02-17 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text='Enter room number', max_length=20)),
                ('room_maxusers', models.IntegerField(help_text='Enter maximum # of room users')),
                ('room_count', models.IntegerField(help_text='Enter # of rooms in this Dorm room')),
                ('room_dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorms.Dorm')),
            ],
            options={
                'ordering': ('room_number',),
            },
        ),
    ]
