# Generated by Django 2.0.2 on 2018-02-24 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorms', '0004_auto_20180218_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormRoomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorm_image', models.ImageField(help_text='Upload a room image', upload_to='')),
                ('dorm_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dorms.DormRoom')),
            ],
        ),
    ]
