# Generated by Django 2.0.2 on 2018-02-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorms', '0002_dormroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(help_text='Enter the school', max_length=50)),
                ('dorms_list', models.ManyToManyField(to='dorms.Dorm')),
            ],
            options={
                'ordering': ('school_name',),
            },
        ),
    ]
