# Generated by Django 2.0.2 on 2018-02-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorms', '0003_dormschool'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormschool',
            name='school_description',
            field=models.CharField(help_text='Enter the school description', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dormschool',
            name='school_logo',
            field=models.ImageField(blank=True, default=None, help_text='Upload school logo', null=True, upload_to=''),
        ),
    ]
