# Generated by Django 2.0.2 on 2018-03-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorms', '0005_dormroomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormroom',
            name='room_availability',
            field=models.CharField(blank=True, default=None, help_text='Is room available', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dormroom',
            name='room_caretaker',
            field=models.CharField(blank=True, default=None, help_text='Enter room caretaker name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dormroom',
            name='room_contact_email',
            field=models.EmailField(blank=True, default=None, help_text='Enter room email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='dormroom',
            name='room_contact_no',
            field=models.CharField(blank=True, default=None, help_text='Enter room contact number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dormroom',
            name='room_date_added',
            field=models.DateTimeField(blank=True, default=None, help_text='Enter Date room was created', null=True),
        ),
        migrations.AddField(
            model_name='dormroom',
            name='room_date_updated',
            field=models.DateTimeField(blank=True, default=None, help_text='Enter Date Room information was updated', null=True),
        ),
        migrations.AddField(
            model_name='dormroom',
            name='room_description',
            field=models.TextField(blank=True, default=None, help_text='Enter dorm description', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dormroom',
            name='room_floor',
            field=models.CharField(blank=True, default=None, help_text='Enter the floor this room belongs to', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dormroom',
            name='room_house_rules',
            field=models.TextField(blank=True, default=None, help_text='Enter room house rules', max_length=1000, null=True),
        ),
    ]
