# Generated by Django 2.0.2 on 2018-03-02 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorms', '0006_auto_20180303_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormRoomAmenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_aircon', models.CharField(help_text='Enter Aircon Type', max_length=50)),
                ('room_wifi', models.CharField(help_text='Enter Wifi details', max_length=50)),
                ('room_kitchen', models.CharField(help_text='Enter Kitchen details', max_length=50)),
                ('room_fireextenguisher', models.CharField(help_text='Enter Fire details', max_length=50)),
                ('room_tv', models.CharField(help_text='Enter Fire details', max_length=50)),
                ('room_washing', models.CharField(help_text='Enter Fire details', max_length=50)),
                ('dorm_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='dorms.DormRoom')),
            ],
        ),
    ]
